/*
* generated by Xtext
*/
package org.modaptix.mumads.dsl.mpadl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MpadlStandaloneSetup extends MpadlStandaloneSetupGenerated{

	public static void doSetup() {
		new MpadlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

