/*
 * generated by Xtext
 */
package org.modaptix.mumads.dsl.mcudl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class McudlUiModule extends org.modaptix.mumads.dsl.mcudl.ui.AbstractMcudlUiModule {
	public McudlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
