/*
 * generated by Xtext
 */
package org.modaptix.mumads.dsl.mpadl.ui.contentassist

import org.modaptix.mumads.dsl.mpadl.ui.contentassist.AbstractMpadlProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MpadlProposalProvider extends AbstractMpadlProposalProvider {
}
