/*
 * generated by Xtext
 */
package org.modaptix.mumads.dsl.mpadl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.modaptix.mumads.dsl.mpadl.ui.MpadlHighlightingCalculator;
import org.modaptix.mumads.dsl.mpadl.ui.MpadlHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MpadlUiModule extends
		org.modaptix.mumads.dsl.mpadl.ui.AbstractMpadlUiModule
{
	public MpadlUiModule(AbstractUIPlugin plugin)
	{
		super(plugin);
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration()
	{
		return MpadlHighlightingConfiguration.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator()
	{
		return MpadlHighlightingCalculator.class;
	}
}
