/*
 * generated by Xtext
 */
package org.modaptix.mumads.dsl.asm.ui.contentassist

import org.modaptix.mumads.dsl.asm.ui.contentassist.AbstractAsmProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AsmProposalProvider extends AbstractAsmProposalProvider {
}
