/*
 * generated by Xtext
 */
package org.modaptix.mumads.dsl.mcudl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class McudlRuntimeModule extends org.modaptix.mumads.dsl.mcudl.AbstractMcudlRuntimeModule {

}
