/*
* generated by Xtext
*/
package org.modaptix.mumads.dsl.mcudl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class McudlStandaloneSetup extends McudlStandaloneSetupGenerated{

	public static void doSetup() {
		new McudlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

