/*
 * generated by Xtext
 */
package org.modaptix.mumads.dsl.asm;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.modaptix.mumads.dsl.mpadl.util.filelocator.MumadsProjectPreferences;
import org.modaptix.mumads.dsl.mpadl.util.interfaces.IMumadsProjectPreferences;
import org.modaptix.xtext.expressions.TerminalConverters;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class AsmRuntimeModule extends org.modaptix.mumads.dsl.asm.AbstractAsmRuntimeModule
{
	//public Class<? extends IMpadlLocator> bindIMpadlLocator() {
	//	return MpadlLocator.class;
	//}
	
	public Class<? extends IMumadsProjectPreferences> bindIMumadsProjectPreferences()
	{
		return MumadsProjectPreferences.class;
	}
	
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService()
	{
		return TerminalConverters.class;
	}
}
