/*
 * generated by Xtext
 */
package org.modaptix.mumads.dsl.asm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AsmRuntimeModule extends org.modaptix.mumads.dsl.asm.AbstractAsmRuntimeModule {

}
