/*
* generated by Xtext
*/
package org.modaptix.mumads.dsl.asm;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AsmStandaloneSetup extends AsmStandaloneSetupGenerated{

	public static void doSetup() {
		new AsmStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

