/*
 * generated by Xtext
 */
package org.modaptix.mumads.dsl.mcudl.ui.contentassist

import org.modaptix.mumads.dsl.mcudl.ui.contentassist.AbstractMcudlProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class McudlProposalProvider extends AbstractMcudlProposalProvider {
}
